import type { Metadata } from 'next'
import { IBM_Plex_Sans_Arabic } from 'next/font/google'
import './globals.css'
const inter = IBM_Plex_Sans_Arabic({ subsets: ['latin'], weight: ['200'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="ar" dir='rtl'>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
